# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d479ec0c6bce744f612986e04229cd0fb3d9aad6ae863d149fedadd6f06072a81315399586202a3945a398ffa6a69e51445b75492d9e2c555bafbee74067133

test:
  secret_key_base: 220c6d6c98f7e4f48bf3669ae42b49916d03b93ce80ebef10d4721cc47833bfd03b5ed1b07e501bf80eb6452ac9fb202ab7fca9479c18c5fd9deea68ed000420

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
